# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Body(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, time_series: List[float]=None):  # noqa: E501
        """Body - a model defined in Swagger

        :param time_series: The time_series of this Body.  # noqa: E501
        :type time_series: List[float]
        """
        self.swagger_types = {
            'time_series': List[float]
        }

        self.attribute_map = {
            'time_series': 'time_series'
        }
        self._time_series = time_series

    @classmethod
    def from_dict(cls, dikt) -> 'Body':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The body of this Body.  # noqa: E501
        :rtype: Body
        """
        return util.deserialize_model(dikt, cls)

    @property
    def time_series(self) -> List[float]:
        """Gets the time_series of this Body.


        :return: The time_series of this Body.
        :rtype: List[float]
        """
        return self._time_series

    @time_series.setter
    def time_series(self, time_series: List[float]):
        """Sets the time_series of this Body.


        :param time_series: The time_series of this Body.
        :type time_series: List[float]
        """

        self._time_series = time_series
