openapi: 3.0.0
info:
  title: sktime forecast
  version: 0.0.1
servers:
- url: http://localhost:3000
paths:
  /forecast:
    post:
      description: Sending time series which needs to be forecasted
      operationId: app_naive_forecast
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/body'
        required: true
      responses:
        "200":
          description: response with time series forecast
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      x-openapi-router-controller: swagger_server.controllers.default_controller
components:
  schemas:
    Error:
      required:
      - code
      - message
      type: object
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
    body:
      properties:
        time_series:
          type: array
          items:
            type: number
    inline_response_200:
      properties:
        forecast:
          type: array
          items:
            type: number
      example:
        forecast:
        - 0.80082819046101150206595775671303272247314453125
        - 0.80082819046101150206595775671303272247314453125

